// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: async_messaging/consumer_service.proto

package asyncMessaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceivedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Body  string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Topic string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// SentTimestamp and possibly TraceId
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedMessage) Reset() {
	*x = ReceivedMessage{}
	mi := &file_async_messaging_consumer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedMessage) ProtoMessage() {}

func (x *ReceivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_async_messaging_consumer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedMessage.ProtoReflect.Descriptor instead.
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return file_async_messaging_consumer_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReceivedMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ReceivedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReceivedMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var file_async_messaging_consumer_service_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "accelbyte.extend.async_messaging.topics_subscription",
		Tag:           "bytes,50001,opt,name=topics_subscription",
		Filename:      "async_messaging/consumer_service.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string topics_subscription = 50001;
	E_TopicsSubscription = &file_async_messaging_consumer_service_proto_extTypes[0]
)

var File_async_messaging_consumer_service_proto protoreflect.FileDescriptor

const file_async_messaging_consumer_service_proto_rawDesc = "" +
	"\n" +
	"&async_messaging/consumer_service.proto\x12 accelbyte.extend.async_messaging\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/descriptor.proto\"\xd5\x01\n" +
	"\x0fReceivedMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12[\n" +
	"\bmetadata\x18\x03 \x03(\v2?.accelbyte.extend.async_messaging.ReceivedMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa5\x01\n" +
	"\x1dAsyncMessagingConsumerService\x12\x83\x01\n" +
	"\tonMessage\x121.accelbyte.extend.async_messaging.ReceivedMessage\x1a\x16.google.protobuf.Empty\"+\x8a\xb5\x18'PlayerKilled, PlayerSaved, PlayerJoined:Q\n" +
	"\x13topics_subscription\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x12topicsSubscriptionBn\n" +
	"#net.accelbyte.extend.asyncMessagingP\x01Z#accelbyte.net/extend/asyncMessaging\xaa\x02\x1fAccelByte.Extend.AsyncMessagingb\x06proto3"

var (
	file_async_messaging_consumer_service_proto_rawDescOnce sync.Once
	file_async_messaging_consumer_service_proto_rawDescData []byte
)

func file_async_messaging_consumer_service_proto_rawDescGZIP() []byte {
	file_async_messaging_consumer_service_proto_rawDescOnce.Do(func() {
		file_async_messaging_consumer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_async_messaging_consumer_service_proto_rawDesc), len(file_async_messaging_consumer_service_proto_rawDesc)))
	})
	return file_async_messaging_consumer_service_proto_rawDescData
}

var file_async_messaging_consumer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_async_messaging_consumer_service_proto_goTypes = []any{
	(*ReceivedMessage)(nil),            // 0: accelbyte.extend.async_messaging.ReceivedMessage
	nil,                                // 1: accelbyte.extend.async_messaging.ReceivedMessage.MetadataEntry
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
	(*emptypb.Empty)(nil),              // 3: google.protobuf.Empty
}
var file_async_messaging_consumer_service_proto_depIdxs = []int32{
	1, // 0: accelbyte.extend.async_messaging.ReceivedMessage.metadata:type_name -> accelbyte.extend.async_messaging.ReceivedMessage.MetadataEntry
	2, // 1: accelbyte.extend.async_messaging.topics_subscription:extendee -> google.protobuf.MethodOptions
	0, // 2: accelbyte.extend.async_messaging.AsyncMessagingConsumerService.onMessage:input_type -> accelbyte.extend.async_messaging.ReceivedMessage
	3, // 3: accelbyte.extend.async_messaging.AsyncMessagingConsumerService.onMessage:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_async_messaging_consumer_service_proto_init() }
func file_async_messaging_consumer_service_proto_init() {
	if File_async_messaging_consumer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_async_messaging_consumer_service_proto_rawDesc), len(file_async_messaging_consumer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_async_messaging_consumer_service_proto_goTypes,
		DependencyIndexes: file_async_messaging_consumer_service_proto_depIdxs,
		MessageInfos:      file_async_messaging_consumer_service_proto_msgTypes,
		ExtensionInfos:    file_async_messaging_consumer_service_proto_extTypes,
	}.Build()
	File_async_messaging_consumer_service_proto = out.File
	file_async_messaging_consumer_service_proto_goTypes = nil
	file_async_messaging_consumer_service_proto_depIdxs = nil
}
