// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: async_messaging/consumer_service.proto

package asyncMessaging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsyncMessagingConsumerService_OnMessage_FullMethodName = "/accelbyte.extend.async_messaging.AsyncMessagingConsumerService/onMessage"
)

// AsyncMessagingConsumerServiceClient is the client API for AsyncMessagingConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsyncMessagingConsumerServiceClient interface {
	OnMessage(ctx context.Context, in *ReceivedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type asyncMessagingConsumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncMessagingConsumerServiceClient(cc grpc.ClientConnInterface) AsyncMessagingConsumerServiceClient {
	return &asyncMessagingConsumerServiceClient{cc}
}

func (c *asyncMessagingConsumerServiceClient) OnMessage(ctx context.Context, in *ReceivedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AsyncMessagingConsumerService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncMessagingConsumerServiceServer is the server API for AsyncMessagingConsumerService service.
// All implementations should embed UnimplementedAsyncMessagingConsumerServiceServer
// for forward compatibility.
type AsyncMessagingConsumerServiceServer interface {
	OnMessage(context.Context, *ReceivedMessage) (*emptypb.Empty, error)
}

// UnimplementedAsyncMessagingConsumerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsyncMessagingConsumerServiceServer struct{}

func (UnimplementedAsyncMessagingConsumerServiceServer) OnMessage(context.Context, *ReceivedMessage) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedAsyncMessagingConsumerServiceServer) testEmbeddedByValue() {}

// UnsafeAsyncMessagingConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncMessagingConsumerServiceServer will
// result in compilation errors.
type UnsafeAsyncMessagingConsumerServiceServer interface {
	mustEmbedUnimplementedAsyncMessagingConsumerServiceServer()
}

func RegisterAsyncMessagingConsumerServiceServer(s grpc.ServiceRegistrar, srv AsyncMessagingConsumerServiceServer) {
	// If the following call panics, it indicates UnimplementedAsyncMessagingConsumerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsyncMessagingConsumerService_ServiceDesc, srv)
}

func _AsyncMessagingConsumerService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceivedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncMessagingConsumerServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncMessagingConsumerService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncMessagingConsumerServiceServer).OnMessage(ctx, req.(*ReceivedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AsyncMessagingConsumerService_ServiceDesc is the grpc.ServiceDesc for AsyncMessagingConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsyncMessagingConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.extend.async_messaging.AsyncMessagingConsumerService",
	HandlerType: (*AsyncMessagingConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "onMessage",
			Handler:    _AsyncMessagingConsumerService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "async_messaging/consumer_service.proto",
}
